### ISSUE TITLE
when 2 plugins are set on the same page only one will get loaded

### ISSUE THREAD

**Issue by Xippo** [codeseveneleven/mastodon-feed#1]
hi folks,

thanks for your open source contribution with this amazing TYPO3 extension.

I have found a little bug. We have a TYPO3 Ver. 11 instance. When we place 2 times the plugin in on the same page, only the first in the DOM will get loaded. The second is loading forever. When we disable the first, the second loads with out problems.

We try to fetch one hashtag and one profile from mas.to. 

greetings

**Comment by foppelfb** [comment]
please check out the new release, your issue should be fixed there now
