### ISSUE TITLE
Extension is not compatible with PHP 7.4.* like the composer.json says 

### ISSUE THREAD

**Issue by Xippo** [codeseveneleven/mastodon-feed#2]
Thanks for the super quick fix. I found a new compatiblity issue

Uncaught TYPO3 Exception syntax error, unexpected '->' (T_OBJECT_OPERATOR)
thrown in file /var/www/html/web/typo3conf/ext/mastodon_feed/Classes/Controller/FeedController.php
in line 26

This needs PHP 8

Grettings
Oliver

**Comment by pottmar12bis3** [comment]
Thanks to Oliver for reporting this, and big thanks to Stefan for fixing this and many more pull requests.
